Upgrade to Consul 1.0.0
This commit bumps the blueprint to Consul 1.0.0 REL. A few things have changed
in our Consul cluster pattern that are worth noting.

* HCL is now Consul's configuration format
* `recursor` has been renamed to a list called `recursors`
* Remove Consul UI downloading as an extra step in Dockerfile
* Consul UI is now included in the dist so we've enabled it by default
* Bump Alpine to 3.6 as our base images
* Bump ContainerPilot to 3.6.0

diff --git a/bin/consul-manage b/bin/consul-manage
--- a/bin/consul-manage
+++ b/bin/consul-manage
@@ -1,20 +1,26 @@
 #!/bin/bash
 set -eo pipefail
 
-# Update the -advertise address based on the interface that ContainerPilot
-# has been told to listen on.
+#
+# Update the -advertise address based on the interface that ContainerPilot has
+# been told to listen on.
+#
 preStart() {
     _log "Updating consul advertise address"
-    sed -i "s/CONTAINERPILOT_CONSUL_IP/${CONTAINERPILOT_CONSUL_IP}/" /etc/consul/consul.json
+    sed -i "s/CONTAINERPILOT_CONSUL_IP/${CONTAINERPILOT_CONSUL_IP}/" /etc/consul/consul.hcl
 }
 
-# Check if a member of a raft. If consul info returns an error we'll
-# pipefail and exit for a failed health check.
-# If we have no peers then try to join the raft via the CNS svc record.
-# Once a node is connected to at least one other peer it'll get the rest
-# of the raft via the Consul LAN gossip.
-# If we end up joining ourselves we just retry on the next health check
-# until we've got the whole cluster together.
+#
+# Check if a member of a raft. If consul info returns an error we'll pipefail
+# and exit for a failed health check.
+#
+# If we have no peers then try to join the raft via the CNS svc record.  Once a
+# node is connected to at least one other peer it'll get the rest of the raft
+# via the Consul LAN gossip.
+#
+# If we end up joining ourselves we just retry on the next health check until
+# we've got the whole cluster together.
+#
 health() {
     if [ $(consul info | awk '/num_peers/{print$3}') == 0 ]; then
         _log "No peers in raft"
